baseURL = 'https://chandlershaw.com'
languageCode = 'en-us'
title = 'Chandler Shaw PhD'
theme = 'hyde'

[Menus]
main = [
  { Name = "Github", URL = "https://github.com/missladychan" },
  { Name = "LinkedIn", URL = "https://youtu.be/dQw4w9WgXcQ?si=3m_9uJpva3vA5oBq" },
]

[params]
description = "This is a placeholder tagline"
themeColor = "theme-base-0d"

[caches]
[caches.images]
dir = ':cacheDir/images'
